package com.enderlord.vaultmapper.shapes;

public enum VaultShapes {
     DIAMOND1(new boolean[][]{
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
             {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
             {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
             {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
             {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
             {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}
     }),
    DIAMOND2(new boolean[][]{
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}
    }),
    DIAMOND3(new boolean[][]{
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, true , true , true , true , true , true , true , true , true , true , true , false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}
    }),
    DIAMOND4(new boolean[][]{
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, true , true , true , true , true , true , true , true , true , true , true , false, false, false},
        {false, false, true , true , true , true , true , true , true , true , true , true , true , true , true , false, false},
        {false, false, false, true , true , true , true , true , true , true , true , true , true , true , false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}
    }),
    DIAMOND5(new boolean[][]{
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, true , true , true , true , true , true , true , true , true , true , true , false, false, false},
        {false, false, true , true , true , true , true , true , true , true , true , true , true , true , true , false, false},
        {false, true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , false},
        {false, false, true , true , true , true , true , true , true , true , true , true , true , true , true , false, false},
        {false, false, false, true , true , true , true , true , true , true , true , true , true , true , false, false, false},
        {false, false, false, false, true , true , true , true , true , true , true , true , true , false, false, false, false},
        {false, false, false, false, false, true , true , true , true , true , true , true , false, false, false, false, false},
        {false, false, false, false, false, false, true , true , true , true , true , false, false, false, false, false, false},
        {false, false, false, false, false, false, false, true , true , true , false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, true , false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}
    }),
    BIGSQUARE(new boolean[][]{
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
            {true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true , true },
    });
    public boolean[][] predictedSpots;
    VaultShapes(boolean[][] booleans) {
        predictedSpots = booleans;
    }
}
